// Pure template-string builders for `quickadui generate auth` — same
// split as `resource-templates.ts`: these functions only build strings,
// `commands/generate-auth.ts` is the only place that touches the
// filesystem.
//
// Scope, deliberately: login + "who am I" + logout + a profile page.
// No sign-up page is generated. DummyJSON (the default --api-base) has a
// `/users/add` endpoint that *looks* like account creation, but like its
// other write endpoints it doesn't persist anything server-side — a
// generated sign-up form against it would create an account that works
// for exactly one request and is gone on refresh, which is more
// confusing than useful as a first example. Point --api-base at a real
// backend with real sign-up once you have one.

import type { ScaffoldFile } from "../templates.js";

export interface AuthTemplateOptions {
  /** e.g. "https://dummyjson.com" — no trailing slash. */
  readonly apiBase: string;
}

export function renderAuthClient(options: AuthTemplateOptions): ScaffoldFile {
  const { apiBase } = options;

  const contents = `// Generated by \`quickadui generate auth\`, pointed at ${apiBase}.
// Talks to the demo user database at https://dummyjson.com/auth by
// default — sign in with any user listed at https://dummyjson.com/users, e.g.
// username "emilys", password "emilyspass". Point --api-base at your own
// backend and adjust the request/response field names below to match it
// — accessToken/refreshToken/etc. are DummyJSON's own naming, not a
// universal convention.
const API_BASE = "${apiBase}";

export interface AuthUser {
  readonly id: number;
  readonly username: string;
  readonly email: string;
  readonly firstName: string;
  readonly lastName: string;
  readonly image: string;
}

export interface LoginCredentials {
  readonly username: string;
  readonly password: string;
}

export interface LoginResult extends AuthUser {
  readonly accessToken: string;
  readonly refreshToken: string;
}

export async function login(credentials: LoginCredentials): Promise<LoginResult> {
  const response = await fetch(\`\${API_BASE}/auth/login\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(credentials),
  });
  if (!response.ok) {
    throw new Error(
      response.status === 400 ? "Invalid username or password." : \`Login failed (\${response.status}).\`,
    );
  }
  return (await response.json()) as LoginResult;
}

export async function getMe(accessToken: string): Promise<AuthUser> {
  const response = await fetch(\`\${API_BASE}/auth/me\`, {
    headers: { Authorization: \`Bearer \${accessToken}\` },
    credentials: "include",
  });
  if (!response.ok) {
    throw new Error(\`Failed to load the current user (\${response.status}).\`);
  }
  return (await response.json()) as AuthUser;
}

// No logout() here on purpose — there's nothing server-side to revoke
// against a demo API like this one. AuthProvider's logout() just clears
// the locally-stored token; add a real POST /auth/logout call here once
// your backend has a session worth invalidating.
`;

  return { path: "src/auth/auth-client.ts", contents };
}

export function renderAuthProvider(): ScaffoldFile {
  const contents = `import { createContext, type ReactNode, useContext, useEffect, useState } from "react";
import { type AuthUser, getMe, type LoginCredentials, login as loginRequest } from "./auth-client";

const TOKEN_STORAGE_KEY = "quickadui-auth-token";

interface AuthContextValue {
  readonly user: AuthUser | undefined;
  readonly loading: boolean;
  readonly login: (credentials: LoginCredentials) => Promise<void>;
  readonly logout: () => void;
}

const AuthContext = createContext<AuthContextValue | null>(null);

/**
 * Generated by \`quickadui generate auth\`. Wrap your app in
 * <AuthProvider> once, near the root (next to <ThemeProvider>, if you
 * have one) — every page under it can then call useAuth(). The access
 * token is kept in localStorage under "quickadui-auth-token" so a page
 * refresh doesn't sign the person back out; there's no server-side
 * session to revoke against a demo API, so logout() only clears it
 * locally.
 */
export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser | undefined>(undefined);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const storedToken = localStorage.getItem(TOKEN_STORAGE_KEY);
    if (!storedToken) {
      setLoading(false);
      return;
    }
    getMe(storedToken)
      .then(setUser)
      .catch(() => {
        localStorage.removeItem(TOKEN_STORAGE_KEY);
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  async function login(credentials: LoginCredentials) {
    const result = await loginRequest(credentials);
    localStorage.setItem(TOKEN_STORAGE_KEY, result.accessToken);
    setUser(result);
  }

  function logout() {
    localStorage.removeItem(TOKEN_STORAGE_KEY);
    setUser(undefined);
  }

  return <AuthContext.Provider value={{ user, loading, login, logout }}>{children}</AuthContext.Provider>;
}

export function useAuth(): AuthContextValue {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error("useAuth must be used within an <AuthProvider>");
  }
  return context;
}
`;

  return { path: "src/auth/AuthProvider.tsx", contents };
}

export function renderLoginPage(): ScaffoldFile {
  const contents = `import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from "@quickadui/core";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  Input,
  useForm,
  zodResolver,
} from "@quickadui/forms";
import { useState } from "react";
import { z } from "zod";
import { useAuth } from "../auth/AuthProvider";

const loginSchema = z.object({
  username: z.string().min(1, "Required"),
  password: z.string().min(1, "Required"),
});

type LoginValues = z.infer<typeof loginSchema>;

/**
 * Generated by \`quickadui generate auth\`. Try the demo account
 * username "emilys" / password "emilyspass" (any user at
 * https://dummyjson.com/users works) — swap the demo API for your own
 * backend via auth-client.ts's API_BASE once you have one. Navigates to
 * "#/" on success; adjust that (and how this page gets rendered) to
 * match your own routing.
 */
export function LoginPage() {
  const { login } = useAuth();
  const [error, setError] = useState<string | undefined>(undefined);

  const form = useForm<LoginValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: { username: "", password: "" },
  });

  async function onSubmit(values: LoginValues) {
    setError(undefined);
    try {
      await login(values);
      window.location.hash = "#/";
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center p-4">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>Sign in</CardTitle>
          <CardDescription>Demo account: "emilys" / "emilyspass".</CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-4">
              <FormField
                control={form.control}
                name="username"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Username</FormLabel>
                    <FormControl>
                      <Input {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="password"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Password</FormLabel>
                    <FormControl>
                      <Input type="password" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              {error && <p className="text-sm text-danger-11">{error}</p>}
              <Button type="submit" disabled={form.formState.isSubmitting}>
                Sign in
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
}
`;

  return { path: "src/pages/LoginPage.tsx", contents };
}

export function renderProfilePage(): ScaffoldFile {
  const contents = `import { Avatar, AvatarFallback, AvatarImage, Button, Card, CardContent, CardHeader, CardTitle } from "@quickadui/core";
import { useAuth } from "../auth/AuthProvider";

/**
 * Generated by \`quickadui generate auth\`. Only renders something useful
 * once a user is signed in — pair it with your own check (or a
 * ProtectedRoute) before routing to it, since useAuth()'s user is
 * undefined until AuthProvider finishes loading and someone has logged
 * in.
 */
export function ProfilePage() {
  const { user, logout } = useAuth();

  if (!user) {
    return <p className="text-sm text-neutral-11">Not signed in.</p>;
  }

  const initials = \`\${user.firstName.charAt(0)}\${user.lastName.charAt(0)}\`;

  return (
    <div className="flex flex-col gap-4 p-4">
      <Card className="max-w-sm">
        <CardHeader className="flex flex-row items-center gap-3">
          <Avatar>
            <AvatarImage src={user.image} alt="" />
            <AvatarFallback>{initials}</AvatarFallback>
          </Avatar>
          <div>
            <CardTitle>
              {user.firstName} {user.lastName}
            </CardTitle>
            <p className="text-sm text-neutral-11">{user.email}</p>
          </div>
        </CardHeader>
        <CardContent>
          <Button variant="outline" onClick={logout}>
            Log out
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
`;

  return { path: "src/pages/ProfilePage.tsx", contents };
}

/**
 * All four files `generate auth` writes, as pure (path, contents) pairs —
 * `commands/generate-auth.ts` is the only place that touches the
 * filesystem.
 */
export function renderAuthFiles(options: AuthTemplateOptions): readonly ScaffoldFile[] {
  return [renderAuthClient(options), renderAuthProvider(), renderLoginPage(), renderProfilePage()];
}
