// Pure template-string builder for `quickadui apply`'s `dashboard`
// section — same "pure builder here, filesystem writes only in
// commands/" split as resource-templates.ts/app-shell-templates.ts use.
// Unlike those two, this is only reachable via `apply` today (there's no
// standalone `quickadui generate dashboard` subcommand, matching
// `theme`/`toasts`/`confirmDelete`'s own "config-only, no flag" pattern
// — a dashboard only makes sense once at least one resource already
// exists, so composing it by hand as a fourth generate step never came
// up the way it did for resource/auth/app).
//
// Each widget renders as its own small function component with its own
// independent `useEffect` fetch — a "stat" widget calls the resource's
// own `list<Type>()` (already generated by `generate resource`) with
// `limit: 1` and reads `.total`; a "list" widget calls the same function
// with the configured `limit` and previews the first field of each row.
// No new API surface is invented: both widget types are answered by the
// exact same list endpoint every resource's own ListPage already calls,
// which is also the honest reading of "an API responsible for the
// computation" for a naive REST backend — the list endpoint's own
// `total` *is* the count, computed server-side already.

import type { ScaffoldFile } from "../templates.js";
import { toKebabCase, toNaivePlural, toPascalCase } from "./case.js";

export type DashboardWidgetType = "stat" | "list";

/**
 * Resolved reference to the resource a widget reads from. `apply.ts`
 * looks this up from `resources[].name` (already validated to exist by
 * `quickadui-config.ts`'s `parseDashboardWidget`) before calling this
 * generator — this file only ever sees already-resolved names, never the
 * raw config, same separation `resource-templates.ts` keeps from
 * `quickadui-config.ts`.
 */
export interface DashboardWidgetResourceRef {
  /** PascalCase type name, e.g. "Product" — matches what `generate resource` derives from `resources[].name`. */
  readonly typeName: string;
  /** URL path segment *and* the list response's own array key, e.g. "products" — matches `generate resource`'s own `--endpoint` resolution. */
  readonly endpoint: string;
  /** The resource's first declared field name, shown as a "list" widget's row label (`String(item.<primaryField>)`). `undefined` when the resource has no fields — rows fall back to `#<id>`. */
  readonly primaryField?: string;
  /**
   * Mirrors the resource's own `endpoints.list.responseShape` (see
   * `resource-templates.ts`'s `resolveEndpoints`) — `list<Plural>()`'s
   * actual return shape and signature depend on it: `"wrapped"` (the
   * default) takes a `{ limit }` argument and returns
   * `{ total, skip, limit, "<endpoint>": T[] }`; `"array"` takes no
   * argument and resolves straight to `T[]`. Every widget reads from the
   * same generated `list<Plural>()` a resource's own list page does, so
   * it must agree with it here too — this is `apply.ts`'s
   * `resolveDashboardWidgets` resolving the same default `resource-templates.ts`
   * does, not a second independent default.
   */
  readonly responseShape?: "wrapped" | "array";
}

export interface DashboardWidgetOptions {
  readonly id: string;
  readonly type: DashboardWidgetType;
  readonly title: string;
  readonly resource: DashboardWidgetResourceRef;
  /** Only "count" is implemented today — see `quickadui-config.ts`'s own `QuickaduiConfigDashboardWidget.metric` doc comment. */
  readonly metric?: "count";
  /** For `type: "list"` only. Default: `5`. */
  readonly limit?: number;
  /** One of `@quickadui/icons`' exported names, without the `Icon` suffix — same convention as `buttonIcons`/nav item icons. */
  readonly icon?: string;
}

export interface DashboardTemplateOptions {
  readonly widgets: readonly DashboardWidgetOptions[];
  /** Omit for `WidgetGrid`'s own default (3) — same "don't restate a component's own default" choice `app-shell-templates.ts`'s `defaultTheme`/`defaultColors` made. */
  readonly columns?: 1 | 2 | 3 | 4;
}

/**
 * Derives a valid JS function identifier from a widget's `id` —
 * "products-count" -> "ProductsCountWidget". Unlike `resources[].name`
 * (fed through `toPascalCase` alone elsewhere in this codebase), a
 * dashboard widget `id` is free-form config text with no "must look like
 * a type name" expectation, so any character `toPascalCase`'s own
 * `[\s_-]+` splitter wouldn't handle (a quote, a slash, a leading digit)
 * is scrubbed first rather than assumed away. Two widgets whose ids
 * sanitize to the same identifier still collide (a rare edge case, not
 * guarded against here — `quickadui-config.ts` only rejects *identical*
 * ids, which is the common typo this actually catches).
 */
function widgetFunctionName(id: string): string {
  const cleaned = id.replace(/[^a-zA-Z0-9\s_-]/g, " ");
  const pascal = toPascalCase(cleaned);
  const safe = pascal.length === 0 || /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
  return `${safe}Widget`;
}

/** One `import { XIcon, YIcon } from "@quickadui/icons";` line, or `""` when no widget sets `icon` — mirrors `resource-templates.ts`'s own `iconImportLine`, duplicated rather than imported since these two template modules are deliberately independent of each other. */
function iconImportLine(widgets: readonly DashboardWidgetOptions[]): string {
  const names = [
    ...new Set(widgets.map((w) => w.icon).filter((name): name is string => name !== undefined)),
  ].sort();
  if (names.length === 0) {
    return "";
  }
  return `import { ${names.map((name) => `${name}Icon`).join(", ")} } from "@quickadui/icons";\n`;
}

function iconJsx(name: string | undefined): string {
  return name !== undefined ? `<${name}Icon size={16} aria-hidden />` : "";
}

/** `"..."` — a JS string literal, quote/backslash-safe. Widget `title`s and resource `typeName`/`endpoint` all ultimately come from a JSON config, so embedding them as raw template-string text (rather than through this) risks a broken generated file on a title containing `"` or a backtick. Mirrors `resource-templates.ts`'s own `jsString`, duplicated for the same "independent template modules" reason as `iconImportLine` above. */
function jsString(value: string): string {
  return JSON.stringify(value);
}

function renderStatWidget(widget: DashboardWidgetOptions): string {
  const { typeName } = widget.resource;
  const isArray = widget.resource.responseShape === "array";
  const plural = toNaivePlural(typeName);
  const fnName = widgetFunctionName(widget.id);
  const icon = iconJsx(widget.icon);
  // "array"-shaped resources' list<Plural>() takes no argument and
  // resolves straight to T[] — there's no server-side `.total` to read,
  // so the count is the fetched array's own length. "wrapped" (the
  // default) keeps asking for just one row and reading the server's own
  // `.total`, same as before this branch existed.
  const listCall = isArray ? `list${plural}()` : `list${plural}({ limit: 1 })`;
  const totalExpr = isArray ? "result.length" : "result.total";

  return `function ${fnName}() {
  const [total, setTotal] = useState<number | undefined>(undefined);
  const [error, setError] = useState<string | undefined>(undefined);

  useEffect(() => {
    let cancelled = false;
    ${listCall}
      .then((result) => {
        if (!cancelled) {
          setTotal(${totalExpr});
        }
      })
      .catch((cause: unknown) => {
        if (!cancelled) {
          setError(cause instanceof Error ? cause.message : String(cause));
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <Widget id={${jsString(widget.id)}}>
      {error ? (
        <p className="text-sm text-danger-11">{error}</p>
      ) : total === undefined ? (
        <div className="flex justify-center py-4">
          <Spinner size="sm" />
        </div>
      ) : (
        <StatCard label={${jsString(widget.title)}} value={total}${icon ? ` icon={${icon}}` : ""} />
      )}
    </Widget>
  );
}`;
}

function renderListWidget(widget: DashboardWidgetOptions): string {
  const { typeName, endpoint, primaryField } = widget.resource;
  const isArray = widget.resource.responseShape === "array";
  const plural = toNaivePlural(typeName);
  const limit = widget.limit ?? 5;
  const fnName = widgetFunctionName(widget.id);
  const icon = iconJsx(widget.icon);
  const titleProp = icon
    ? `{<span className="flex items-center gap-2">${icon}{${jsString(widget.title)}}</span>}`
    : `{${jsString(widget.title)}}`;
  // biome-ignore lint/suspicious/noTemplateCurlyInString: the else-branch string is literal generated-code text (`#${item.id}`), not a template interpolation in this file.
  const rowLabel = primaryField !== undefined ? `String(item.${primaryField})` : "`#${item.id}`";
  // "array"-shaped resources' list<Plural>() takes no argument and
  // resolves straight to T[] — there's no server-side `limit` to ask
  // for, so the preview is truncated client-side after the fetch.
  // "wrapped" (the default) keeps asking the server for `limit` rows and
  // reading them back out from under the endpoint's own key, same as
  // before this branch existed. Reading `result["${endpoint}"]` on a
  // bare array (the bug this branch fixes) silently resolved to
  // `undefined` — `items.map` then threw at render, not at fetch time,
  // which is why it surfaced as a blank-page crash instead of the
  // widget's own `error` state.
  const listCall = isArray ? `list${plural}()` : `list${plural}({ limit: ${limit} })`;
  const itemsExpr = isArray ? `result.slice(0, ${limit})` : `result["${endpoint}"]`;

  return `function ${fnName}() {
  const [items, setItems] = useState<readonly ${typeName}[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | undefined>(undefined);

  useEffect(() => {
    let cancelled = false;
    ${listCall}
      .then((result) => {
        if (!cancelled) {
          setItems(${itemsExpr});
        }
      })
      .catch((cause: unknown) => {
        if (!cancelled) {
          setError(cause instanceof Error ? cause.message : String(cause));
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <Widget id={${jsString(widget.id)}} title=${titleProp}>
      {error ? (
        <p className="text-sm text-danger-11">{error}</p>
      ) : loading ? (
        <div className="flex justify-center py-4">
          <Spinner size="sm" />
        </div>
      ) : items.length === 0 ? (
        <p className="text-sm text-neutral-11">Nothing to show yet.</p>
      ) : (
        <ul className="flex flex-col gap-2">
          {items.map((item) => (
            <li key={item.id} className="text-sm text-neutral-12">
              {${rowLabel}}
            </li>
          ))}
        </ul>
      )}
    </Widget>
  );
}`;
}

/** `"quickadui-dashboard-widget-order"` — the `localStorage` key a dragged widget order is remembered under, once at least one widget exists. Shared by every dashboard a single generated app has (there's only ever one `DashboardPage.tsx`), same single-key approach `auth-templates.ts`'s `TOKEN_STORAGE_KEY` already uses for the same reason: one dashboard, one key, no need to namespace it further. */
const WIDGET_ORDER_STORAGE_KEY = "quickadui-dashboard-widget-order";

/**
 * `loadWidgetOrder`/the `useEffect` that saves back to it — the small
 * amount of state `WidgetGrid`'s `onReorder` needs a consumer to own (see
 * `widget-grid.tsx`'s own doc comment: it's a controlled component,
 * a completed drag never reorders anything by itself). Order is
 * remembered per browser via `localStorage`, the same "no backend needed"
 * approach `auth-templates.ts` already uses for the access token — every
 * read/write is wrapped in try/catch and degrades to `DEFAULT_WIDGET_ORDER`
 * on failure, since a private window or blocked storage should never
 * break the dashboard, just leave the order unremembered.
 */
function renderWidgetOrderHelpers(): string {
  return `/**
 * Reads a previously dragged widget order back from localStorage —
 * best-effort only: a private window, blocked storage, or no prior visit
 * all just fall back to DEFAULT_WIDGET_ORDER, same as this dashboard's
 * very first render. Any id from a stale save that no longer matches a
 * configured widget is dropped, and any widget added to "dashboard.widgets"
 * since the last drag is appended at the end, so editing your config never
 * strands a widget out of the returned order.
 */
function loadWidgetOrder(): string[] {
  if (typeof window === "undefined") {
    return DEFAULT_WIDGET_ORDER;
  }
  try {
    const raw = window.localStorage.getItem(WIDGET_ORDER_STORAGE_KEY);
    if (!raw) {
      return DEFAULT_WIDGET_ORDER;
    }
    const parsed: unknown = JSON.parse(raw);
    if (!Array.isArray(parsed)) {
      return DEFAULT_WIDGET_ORDER;
    }
    const known = new Set(DEFAULT_WIDGET_ORDER);
    const kept = parsed.filter((id): id is string => typeof id === "string" && known.has(id));
    const missing = DEFAULT_WIDGET_ORDER.filter((id) => !kept.includes(id));
    return [...kept, ...missing];
  } catch {
    return DEFAULT_WIDGET_ORDER;
  }
}`;
}

/**
 * Generates `src/pages/DashboardPage.tsx` from `dashboard.widgets` — a
 * `WidgetGrid` (from `@quickadui/shell`) of small, independently-fetching
 * widget components, one per configured widget, draggable to reorder
 * (`@quickadui/shell`'s own drag-and-drop, via `WidgetGrid`'s `onReorder`
 * — see `widget-grid.tsx`) whenever there's more than a placeholder to
 * show. The dragged order is remembered per browser via `localStorage`
 * (see `renderWidgetOrderHelpers` above) — no backend/API needed for
 * this either, same "reuse what's already there" approach the widgets'
 * own data-fetching already takes.
 */
export function renderDashboardPage(options: DashboardTemplateOptions): ScaffoldFile {
  const { widgets, columns } = options;

  const statWidgets = widgets.filter((w) => w.type === "stat");
  const listWidgets = widgets.filter((w) => w.type === "list");
  const needsStatCard = statWidgets.length > 0;

  const resourceTypeNames = [...new Set(widgets.map((w) => w.resource.typeName))].sort();
  const listImportLines = resourceTypeNames
    .map((typeName) => {
      const plural = toNaivePlural(typeName);
      const kebab = toKebabCase(typeName);
      return `import { list${plural} } from "../api/${kebab}.api";`;
    })
    .join("\n");
  const schemaImportLines = [...new Set(listWidgets.map((w) => w.resource.typeName))]
    .sort()
    .map(
      (typeName) =>
        `import type { ${typeName} } from "../schemas/${toKebabCase(typeName)}.schema";`,
    )
    .join("\n");

  const widgetFns = widgets
    .map((w) => (w.type === "stat" ? renderStatWidget(w) : renderListWidget(w)))
    .join("\n\n");

  const gridItems = widgets.map((w) => JSON.stringify(w.id)).join(", ");
  const gridColumnsProp = columns !== undefined ? ` columns={${columns}}` : "";
  const widgetElementEntries = widgets
    .map((w) => `    ${jsString(w.id)}: <${widgetFunctionName(w.id)} key={${jsString(w.id)}} />,`)
    .join("\n");

  const body =
    widgets.length === 0
      ? `      <p className="text-sm text-neutral-11">
        No widgets configured yet — add entries to "dashboard.widgets" in your quickadui config.
      </p>`
      : `      <WidgetGrid items={order} onReorder={setOrder}${gridColumnsProp}>
        {order.map((id) => widgetElements[id])}
      </WidgetGrid>`;

  // With zero widgets there's nothing to fetch, drag, animate a Spinner
  // for, or lay out in a grid — every import below exists only to
  // support at least one widget, so all of them (including react's own
  // useEffect/useState) are skipped entirely rather than left unused.
  const importLines =
    widgets.length === 0
      ? ""
      : `import { Spinner } from "@quickadui/core";
${needsStatCard ? 'import { StatCard } from "@quickadui/charts";\n' : ""}${iconImportLine(widgets)}import { Widget, WidgetGrid } from "@quickadui/shell";
import { type ReactNode, useEffect, useState } from "react";
${listImportLines ? `${listImportLines}\n` : ""}${schemaImportLines ? `${schemaImportLines}\n` : ""}`;

  const dashboardPageFn =
    widgets.length === 0
      ? `export function DashboardPage() {
  return (
    <div className="flex flex-col gap-4">
      <h1 className="text-lg font-semibold text-neutral-12">Dashboard</h1>
${body}
    </div>
  );
}`
      : `export function DashboardPage() {
  const [order, setOrder] = useState<string[]>(loadWidgetOrder);

  useEffect(() => {
    try {
      window.localStorage.setItem(WIDGET_ORDER_STORAGE_KEY, JSON.stringify(order));
    } catch {
      // Best-effort only — see loadWidgetOrder above. A private window
      // or blocked storage just means the order isn't remembered next
      // visit, not a broken dashboard.
    }
  }, [order]);

  const widgetElements: Record<string, ReactNode> = {
${widgetElementEntries}
  };

  return (
    <div className="flex flex-col gap-4">
      <h1 className="text-lg font-semibold text-neutral-12">Dashboard</h1>
${body}
    </div>
  );
}`;

  const orderHelpersBlock =
    widgets.length === 0
      ? ""
      : `const WIDGET_ORDER_STORAGE_KEY = ${jsString(WIDGET_ORDER_STORAGE_KEY)};
const DEFAULT_WIDGET_ORDER = [${gridItems}];

${renderWidgetOrderHelpers()}

`;

  const headerComment =
    widgets.length === 0
      ? `/**
 * Generated by \`quickadui apply\` from your config's "dashboard" section
 * — currently empty. Add entries to "dashboard.widgets" and re-run
 * \`quickadui apply\` (with --force) to fill this page in.
 */`
      : `/**
 * Generated by \`quickadui apply\` from your config's "dashboard" section.
 * Each widget below fetches its own data independently — a "stat"
 * widget reads the total count from its resource's own list endpoint
 * (\`.total\`), a "list" widget previews that endpoint's first few rows.
 * Widgets can be dragged to reorder (a drag-and-drop grid from
 * \`@quickadui/shell\`) — the order is remembered per browser via
 * localStorage, not sent anywhere. Which widgets exist, and their
 * columns, still come from "dashboard.widgets"/"dashboard.columns" —
 * re-running \`quickadui apply\` overwrites this file (only with
 * --force), so keep any hand edits in mind before regenerating.
 */`;

  const contents = `${importLines}${headerComment}

${orderHelpersBlock}${widgetFns}

${dashboardPageFn}
`;

  return { path: "src/pages/DashboardPage.tsx", contents };
}
