import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  // Declarations are generated by a separate `tsc --emitDeclarationOnly`
  // step (see package.json's "build" script), not by tsup's bundled
  // rollup-plugin-dts — that plugin's own vendored TS internals aren't
  // compatible with TypeScript 7 (`Cannot read properties of undefined
  // (reading 'useCaseSensitiveFileNames')`), while the project's own `tsc`
  // (the same binary "typecheck" already runs) works fine.
  dts: false,
  sourcemap: true,
  clean: true,
  // @quickadui/tokens is a real workspace dependency — external so it's
  // resolved via node_modules instead of duplicated into this bundle.
  external: ["react", "react-dom", "@quickadui/tokens"],
});
