import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  // Declarations are generated by a separate `tsc --emitDeclarationOnly`
  // step (see package.json's "build" script), not by tsup's bundled
  // rollup-plugin-dts — see `@quickadui/shell`'s tsup.config.ts for why.
  dts: false,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
});
