import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  // Declarations are generated by a separate `tsc --emitDeclarationOnly`
  // step (see package.json's "build" script), not by tsup's bundled
  // rollup-plugin-dts — that plugin's own vendored TS internals aren't
  // compatible with TypeScript 7 (`Cannot read properties of undefined
  // (reading 'useCaseSensitiveFileNames')`), while the project's own `tsc`
  // (the same binary "typecheck" already runs) works fine.
  dts: false,
  sourcemap: true,
  clean: true,
  // @quickadui/primitives and @quickadui/utils are real workspace
  // dependencies — external so they're resolved via node_modules once,
  // instead of duplicated into every package that bundles them.
  external: ["react", "react-dom", "@quickadui/primitives", "@quickadui/utils"],
});
